# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cfb298aa1a00e3a0ecb98e61df654a33873715a473a464eec506f784e05b499e4f070bca908be7ac7baebff8d36329c9df561bf8739fa9cfb6fe15eb2f3d031

test:
  secret_key_base: 468be1e298e2a23faf5a56841f036e9325beacd22a39fb1ce6af1dfba8c2c6f09955134553ced2a1b5c2098292dd2eaf2fe51e2fec7da9958412b65e3f819118

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
